name: delve_app
description: Event Management

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cuberto_bottom_bar: ^1.1.1
  cupertino_icons: ^0.1.2
  get_it: ^4.0.2
  shared_preferences: ^0.5.8
  flutter_cache_manager: ^1.4.1
  provider: ^4.3.1
  cached_network_image: ^2.2.0+1
  url_launcher: ^5.5.0
  intl: ^0.16.1
  intent: ^1.3.4
  open_file: ^3.0.1
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.16
  flutter_uploader: ^1.2.0
  image_picker: 0.6.2
  image_cropper: ^1.2.3
  flutter_html: ^1.0.0-pre.1
  flutter_downloader: ^1.5.0
  flutter_widget_from_html: ^0.5.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Raleway-Light
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf

    - family: Raleway-Medium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf

    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf

    - family: Raleway-Regular
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
